name: test

on: 

  push:

    branches:

          - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: trigger multiple Job

        uses: appleboy/jenkins-action@master

        with:

          url: "http://localhost:8080/"

          user: "testAutomation"

          token: ${secrets.TOKEN}

          job: "java-selenium"
