name: test

on: 

  push:

    branches:

          - main
env:
  JENKINS_HOST: "http://localhost:80"

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: trigger single Job

        uses: appleboy/jenkins-action@master

        with:

          url: ${{env.JENKINS_HOST}}

          user: ${{secrets.Jenkins_Name}}

          token: ${{secrets.TOKEN}}

          job: "java-selenium"
